<?php
/******************************************
US English
Admin Category Language
******************************************/

$lang['categories']					= 'Galleries';
$lang['error_must_select']			= 'Vous devez sélectionner une gallerie pour organiser';
$lang['error_not_found']			= 'La gallerie demandée n\'a pas pu être trouvé.';
$lang['organize_category']			= '"%s" gallerie Organiser  ';
$lang['organize']					= 'Organiser';
$lang['category_id']				= 'ID';
$lang['category_form']				= 'Formulaire gallerie' ;
$lang['name']						= 'Nom';
$lang['slug']						= 'Jeton';
$lang['description']				= 'Déscription';
$lang['excerpt']					= 'Extrait';
$lang['sequence']					= 'Séquence';
$lang['image']						= 'Image';
$lang['seo_title']					= 'SEO Title';
$lang['meta']						= 'Meta Data';
$lang['message_category_saved']		= 'La gallerie a été enregistré!';
$lang['error_file_upload']			= '<p>Vous n\'avez pas sélectionné un fichier à télécharger.</p>'; //important. This must match the same error as generated by the file upload script of your language.
$lang['message_delete_category']	= 'La gallerie a été supprimé.';
$lang['current_file']				= 'Fichier actuel';
$lang['confirm_delete_category']	= 'Êtes-vous sûr de vouloir supprimer cette gallerie?';
$lang['add_new_category']			= 'Ajouter gallerie';
$lang['top_level_category']         = 'gallerie Niveau supérieur';
$lang['no_categories']				= 'Il n\'y a pas de galleries';
$lang['attributes']					= 'Attributs';
$lang['seo']						= 'SEO';
$lang['parent']						= 'Parent';
$lang['meta_data_description']		= 'ex. &lt;meta name="description" content="Nous vendons des produits qui vous aident" /&gt;';
$lang['drag_and_drop']				= 'Faites glisser et déposez les produits dans l\'ordre que vous souhaitez les voir apparaître.';
$lang['sku']						= 'Réf';
$lang['price']						= 'Prix';
$lang['sale']						= 'Vente';
$lang['max_file_size']				= 'Taille maximale du fichier';