<?php
/******************************************
US English
Admin Category Language
******************************************/

$lang['categories']					= 'Categories';
$lang['error_must_select']			= 'You must select a gallery to organize';
$lang['error_not_found']			= 'The requested gallery could not be found.';
$lang['organize_category']			= '"%s" Organize Category  ';
$lang['organize']					= 'Organize';
$lang['category_id']				= 'Category ID';
$lang['category_form']				= 'Category form' ;
$lang['name']						= 'Name';
$lang['slug']						= 'Slug';
$lang['description']				= 'Description';
$lang['excerpt']					= 'Excerpt';
$lang['sequence']					= 'Sequence';
$lang['image']						= 'Image';
$lang['seo_title']					= 'SEO Title';
$lang['meta']						= 'Meta Data';
$lang['message_category_saved']		= 'The gallery has been registered!';
$lang['error_file_upload']			= '<p>You haven\'t selected a file to download.</p>'; //important. This must match the same error as generated by the file upload script of your language.
$lang['message_delete_category']	= 'The gallery has been deleted.';
$lang['current_file']				= 'Current file';
$lang['confirm_delete_category']	= 'Are you sure you want to delete this gallery?';
$lang['add_new_category']			= 'Add new category';
$lang['top_level_category']         = 'Top level category';
$lang['no_categories']				= 'No categories';
$lang['attributes']					= 'Attributes';
$lang['seo']						= 'SEO';
$lang['parent']						= 'Parent';

$lang['meta_data_description']		= 'ex. &lt;meta name="description" content="We sell products that help you" /&gt;';
$lang['drag_and_drop']				= 'Drag and drop products in the order you want them to appear.';
$lang['sku']						= 'Sku';
$lang['price']						= 'Price';
$lang['sale']						= 'Sale';
$lang['max_file_size']				= 'Max file size';